version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: mextify_db
    restart: always
    environment:
      POSTGRES_USER: mextify
      POSTGRES_PASSWORD: mextify_password
      POSTGRES_DB: mextify
    ports:
      - '5432:5432'
    volumes:
      - mextify_pgdata:/var/lib/postgresql/data

volumes:
  mextify_pgdata:
